# Generated by Django 3.2.9 on 2021-12-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
    ]
