# Generated by Django 3.2.9 on 2021-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('emailID', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('committee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('committee_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'committee',
            },
        ),
        migrations.CreateModel(
            name='committee_members',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('committee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'committee_members',
            },
        ),
        migrations.CreateModel(
            name='resource_logbook',
            fields=[
                ('log_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_id', models.CharField(max_length=100)),
                ('admin_id', models.CharField(max_length=100)),
                ('resource_id', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
            ],
            options={
                'db_table': 'resource_logbook',
            },
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('resource_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=250)),
                ('OEM', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=100)),
                ('unit_cost', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('purchase_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('about', models.CharField(max_length=400)),
                ('admin_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('tender_id', models.IntegerField(primary_key=True, serialize=False)),
                ('OEM', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('unit_cost', models.IntegerField()),
                ('resource_name', models.CharField(max_length=250)),
                ('tender_issue_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('about', models.CharField(max_length=400)),
                ('admin_id', models.CharField(max_length=100)),
                ('committee_id', models.IntegerField()),
                ('approval_date', models.DateField()),
            ],
            options={
                'db_table': 'tender',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('emailID', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
