# Generated by Django 3.2.9 on 2021-12-16 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=15)),
                ('emailID', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('committee_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('committee_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'committee',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='hello/')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('emailID', models.EmailField(max_length=100)),
                ('USN', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('tender_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('OEM', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('unit_cost', models.IntegerField()),
                ('resource_name', models.CharField(max_length=250)),
                ('tender_issue_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('about', models.CharField(max_length=400)),
                ('approval_date', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins')),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.committee')),
            ],
            options={
                'db_table': 'tender',
            },
        ),
        migrations.CreateModel(
            name='resources',
            fields=[
                ('resource_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=250)),
                ('OEM', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=100)),
                ('unit_cost', models.IntegerField()),
                ('location', models.CharField(max_length=250)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='hello/')),
                ('about', models.CharField(max_length=400)),
                ('admin_id', models.ForeignKey(default='r0Fi0ITEUSMcLPxf2JXUxL3VNK03', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins')),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='resource_logbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources')),
            ],
            options={
                'db_table': 'resource_logbook',
            },
        ),
        migrations.CreateModel(
            name='committee_members',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('emailID', models.EmailField(max_length=100)),
                ('committee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.committee')),
            ],
            options={
                'db_table': 'committee_members',
            },
        ),
    ]
