# Generated by Django 3.2.9 on 2021-12-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_logbook',
            name='id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='id',
        ),
        migrations.AddField(
            model_name='resource_logbook',
            name='log_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='test',
            name='test_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
