# Generated by Django 3.2.9 on 2021-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0003_alter_resources_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
