# Generated by Django 3.2.9 on 2021-12-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0003_auto_20211216_1531'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committee_members',
            table=None,
        ),
    ]
