# Generated by Django 3.2.9 on 2021-12-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0004_alter_committee_members_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
