# Generated by Django 3.2.9 on 2021-12-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0005_alter_tender_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='about',
            field=models.CharField(max_length=1000),
        ),
    ]
