# Generated by Django 3.2.9 on 2021-12-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0006_alter_resources_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_logbook',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users'),
        ),
    ]
