# Generated by Django 3.2.9 on 2021-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0007_alter_resource_logbook_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_logbook',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
