# Generated by Django 3.2.9 on 2021-12-21 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0008_alter_resource_logbook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='admin_id',
            field=models.ForeignKey(db_column='admin_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(null=True, upload_to='hello/'),
        ),
    ]
