# Generated by Django 3.2.9 on 2021-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0008_auto_20211215_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='adminId',
            field=models.CharField(max_length=100),
        ),
    ]
