# Generated by Django 3.2.9 on 2021-12-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0009_alter_resources_adminid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='adminId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins'),
        ),
    ]
