# Generated by Django 3.2.9 on 2021-12-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0009_auto_20211221_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='image',
            field=models.ImageField(default=None, upload_to='hello/'),
        ),
    ]
