# Generated by Django 3.2.9 on 2021-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0010_alter_resources_adminid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='adminId',
        ),
    ]
