# Generated by Django 3.2.9 on 2021-12-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0011_alter_resources_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_logbook',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
