# Generated by Django 4.0.1 on 2022-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0012_alter_resource_logbook_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='resoruceRelatedLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'resoruceRelatedLinks',
            },
        ),
    ]
