# Generated by Django 4.0.1 on 2022-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0014_remove_resorucerelatedlinks_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resorucerelatedlinks',
            name='link_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
