# Generated by Django 4.0.1 on 2022-01-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0015_alter_resorucerelatedlinks_link_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resoruceRelatedLinks',
        ),
    ]
