# Generated by Django 4.0.1 on 2022-01-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0016_delete_resorucerelatedlinks'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resources',
            table='resourcess',
        ),
    ]
