# Generated by Django 4.0.1 on 2022-01-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0017_alter_resources_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resources',
            table='resources',
        ),
    ]
