# Generated by Django 4.0.1 on 2022-01-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0018_alter_resources_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceRelatedLinks',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=400)),
                ('heading', models.CharField(default='', max_length=100)),
                ('resoruce_id', models.ForeignKey(db_column='resource_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources')),
            ],
            options={
                'db_table': 'resourceRelatedLinks',
            },
        ),
    ]
