# Generated by Django 4.0.1 on 2022-01-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0019_resourcerelatedlinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerelatedlinks',
            name='resoruce_id',
        ),
        migrations.AddField(
            model_name='resourcerelatedlinks',
            name='resource_id',
            field=models.ForeignKey(db_column='resource_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources'),
        ),
    ]
