# Generated by Django 4.0.1 on 2022-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0020_remove_resourcerelatedlinks_resoruce_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testingModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texter', models.CharField(max_length=100)),
            ],
        ),
    ]
