# Generated by Django 4.0.1 on 2022-01-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0021_testingmodels'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='committee_members',
            table='committee_members',
        ),
    ]
