# Generated by Django 4.0.1 on 2022-01-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0022_alter_committee_members_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testingModels',
        ),
    ]
