# Generated by Django 4.0.1 on 2022-02-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0023_delete_testingmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='resourceUpdateLogbook',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('resource_name', models.CharField(blank=True, max_length=250, null=True)),
                ('OEM', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_cost', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='hello/')),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins')),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources')),
            ],
        ),
    ]
