# Generated by Django 4.0.1 on 2022-02-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0024_resourceupdatelogbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resourceupdatelogbook',
            table='resourceUpdateLogbook',
        ),
    ]
