# Generated by Django 4.0.1 on 2022-02-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0026_rename_location_admins_admin_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='phone_number',
            new_name='phone_no',
        ),
    ]
