# Generated by Django 4.0.1 on 2022-02-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0027_rename_phone_number_admins_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
