# Generated by Django 4.0.1 on 2022-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0028_admins_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='userMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emailID', models.EmailField(max_length=100)),
                ('message', models.CharField(max_length=1500)),
                ('phone_no', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userMessage',
            },
        ),
    ]
