# Generated by Django 4.0.1 on 2022-03-18 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0029_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='emailID',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='member_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users'),
        ),
    ]
