# Generated by Django 4.0.1 on 2022-04-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0030_remove_usermessage_emailid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committee_members',
            name='committee_id',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='committee_id',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='department_name',
            new_name='admin_department_name',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='emailID',
            new_name='admin_emailID',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='first_name',
            new_name='admin_first_name',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='user_id',
            new_name='admin_id',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='last_name',
            new_name='admin_last_name',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='middle_name',
            new_name='admin_middle_name',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='phone_no',
            new_name='admin_phone_no',
        ),
        migrations.DeleteModel(
            name='committee',
        ),
        migrations.DeleteModel(
            name='committee_members',
        ),
        migrations.DeleteModel(
            name='tender',
        ),
    ]
