# Generated by Django 4.0.1 on 2022-04-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0031_remove_committee_members_committee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_logbook',
            name='member_id',
        ),
        migrations.AddField(
            model_name='resource_logbook',
            name='borrower_user_id',
            field=models.ForeignKey(db_column='borrower_user_id', default='', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users'),
        ),
    ]
