# Generated by Django 4.0.1 on 2022-04-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0033_remove_resource_logbook_borrower_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource_logbook',
            name='member_id',
        ),
    ]
