# Generated by Django 4.0.1 on 2022-04-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0034_remove_resource_logbook_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource_logbook',
            name='member_id',
            field=models.ForeignKey(db_column='member_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users'),
        ),
    ]
