# Generated by Django 4.0.1 on 2022-04-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0035_resource_logbook_member_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resource_logbook',
        ),
    ]
