# Generated by Django 4.0.1 on 2022-04-12 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0036_delete_resource_logbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource_logbook',
            fields=[
                ('log_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.admins')),
                ('member_id', models.ForeignKey(db_column='member_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.users')),
                ('resource_id', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources')),
            ],
            options={
                'db_table': 'resource_logbook',
            },
        ),
    ]
