# Generated by Django 4.0.1 on 2022-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0037_resource_logbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerelatedlinks',
            name='url',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
