# Generated by Django 4.0.1 on 2022-04-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0038_alter_resourcerelatedlinks_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerelatedlinks',
            name='hivar',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='resourcerelatedlinks',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
