# Generated by Django 4.0.1 on 2022-04-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0039_resourcerelatedlinks_hivar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerelatedlinks',
            name='resource_id',
            field=models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources'),
        ),
    ]
