# Generated by Django 4.0.1 on 2022-04-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0040_alter_resourcerelatedlinks_resource_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='admin_department_name',
            new_name='admin_department_names',
        ),
    ]
