# Generated by Django 4.0.1 on 2022-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0041_rename_admin_department_name_admins_admin_department_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='admin_department_names',
            new_name='admin_department_name',
        ),
    ]
