# Generated by Django 4.0.1 on 2022-04-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0042_rename_admin_department_names_admins_admin_department_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerelatedlinks',
            name='hivar',
        ),
        migrations.AlterField(
            model_name='resourcerelatedlinks',
            name='resource_id',
            field=models.ForeignKey(blank=True, db_column='resource_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources'),
        ),
    ]
