# Generated by Django 4.0.1 on 2022-04-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0043_remove_resourcerelatedlinks_hivar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerelatedlinks',
            name='resource_id',
        ),
    ]
