# Generated by Django 4.0.1 on 2022-04-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERVIEW', '0044_remove_resourcerelatedlinks_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerelatedlinks',
            name='resource_id',
            field=models.ForeignKey(blank=True, db_column='resource_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='USERVIEW.resources'),
        ),
    ]
